#
# Tweak the redis server
#
# Perhaps with commands:
#     docker build -t solr-emlo:v.v.v .
#     production:
#     docker run --name solr-emlo-1 -p8983:8983 solr-emlo:v.v.v
#     developing:
#     docker run --name solr-emlo-dev-1 -v $(pwd)/solr/home:/opt/solr/server/solr/home -p8983:8983 solr-emlo:0.1.0
FROM redis:3.2