#
# Tweak the redis server
#
# Perhaps with commands:
#     docker build -t redis-emlo:0.1.0 .
#     production:
#     docker run --name redis-emlo -p 6379:6379 -d redis-emlo:0.1.0
#     developing:
#     docker run --name redis-emlo-dev -p 6379:6379 redis-emlo:0.1.0
FROM redis:3.2

LABEL version="0.1.0"